using System.Collections.Immutable;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Meridian.Analyzer.Tests;

public sealed class MER0027AvoidLongBooleanChainsAnalyzerTests
{
    [Fact]
    public async Task ReportsDiagnostic_ForLongLogicalAndChainAsync()
    {
        const string source = """
public static class Sample
{
    public static bool Match(bool a, bool b, bool c, bool d, bool e, bool f)
    {
        return a && b && c && d && e && f;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source);

        diagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == MER0027AvoidLongBooleanChainsAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task ReportsDiagnostic_ForMixedLogicalChainInsideTernaryConditionAsync()
    {
        const string source = """
public static class Sample
{
    public static int Match(bool a, bool b, bool c, bool d, bool e, bool f)
    {
        return a || b || c || d || e || f ? 1 : 0;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source);

        diagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == MER0027AvoidLongBooleanChainsAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task DoesNotReport_ForShortLogicalChainAsync()
    {
        const string source = """
public static class Sample
{
    public static bool Match(bool a, bool b, bool c, bool d)
    {
        return a && b && c && d;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source);

        diagnostics.Should().BeEmpty();
    }

    [Fact]
    public async Task ReportsDiagnostic_OnceForRootLogicalExpressionOnlyAsync()
    {
        const string source = """
public static class Sample
{
    public static bool Match(bool a, bool b, bool c, bool d, bool e, bool f)
    {
        return a && b && c && d && e && f;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source);

        diagnostics.Should().ContainSingle();
    }

    [Fact]
    public async Task DoesNotReport_ForGeneratedCodeAsync()
    {
        const string source = """
// <auto-generated/>
public static class Sample
{
    public static bool Match(bool a, bool b, bool c, bool d, bool e, bool f)
    {
        return a && b && c && d && e && f;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source, path: "Sample.g.cs");

        diagnostics.Should().BeEmpty();
    }

    private static async Task<ImmutableArray<Diagnostic>> GetDiagnosticsAsync(string source, string path = "src/Infrastructure/Repositories/Repo.cs")
    {
        return await AnalyzerTestHost.GetDiagnosticsAsync(
            source,
            new MER0027AvoidLongBooleanChainsAnalyzer(),
            path);
    }
}
