using System.Collections.Immutable;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Meridian.Analyzer.Tests;

public sealed class MER0026AvoidNestedTernaryChainsAnalyzerTests
{
    [Fact]
    public async Task ReportsDiagnostic_ForDeepTernaryChainInReturnStatementAsync()
    {
        const string source = """
public static class Sample
{
    public static int Classify(bool isRailCode, bool hasRailName, bool hasTrainName, bool looksLikeStation, bool isBus)
    {
        return isRailCode
            ? 0
            : hasRailName
                ? 1
                : hasTrainName
                    ? 2
                    : looksLikeStation && !isBus
                        ? 3
                        : 99;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source);

        diagnostics.Should().ContainSingle(diagnostic => diagnostic.Id == MER0026AvoidNestedTernaryChainsAnalyzer.DiagnosticId);
    }

    [Fact]
    public async Task ReportsDiagnostic_OnceForRootConditionalOnlyAsync()
    {
        const string source = """
public static class Sample
{
    public static int Classify(bool a, bool b, bool c, bool d)
    {
        return a ? 0 : b ? 1 : c ? 2 : d ? 3 : 4;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source);

        diagnostics.Should().ContainSingle();
    }

    [Fact]
    public async Task DoesNotReport_ForShortTernaryChainAsync()
    {
        const string source = """
public static class Sample
{
    public static int Classify(bool isRailCode, bool hasRailName)
    {
        return isRailCode ? 0 : hasRailName ? 1 : 99;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source);

        diagnostics.Should().BeEmpty();
    }

    [Fact]
    public async Task DoesNotReport_ForGeneratedCodeAsync()
    {
        const string source = """
// <auto-generated/>
public static class Sample
{
    public static int Classify(bool a, bool b, bool c, bool d)
    {
        return a ? 0 : b ? 1 : c ? 2 : d ? 3 : 4;
    }
}
""";

        var diagnostics = await GetDiagnosticsAsync(source, path: "Sample.g.cs");

        diagnostics.Should().BeEmpty();
    }

    private static async Task<ImmutableArray<Diagnostic>> GetDiagnosticsAsync(string source, string path = "src/Infrastructure/Repositories/Repo.cs")
    {
        return await AnalyzerTestHost.GetDiagnosticsAsync(
            source,
            new MER0026AvoidNestedTernaryChainsAnalyzer(),
            path);
    }
}
